### ISSUE TITLE
Doesn't work with level@7 and above

### ISSUE THREAD

**Issue by rlidwka** [juliangruber/level-exists#17]
Example in readme shows:

```js
/tmp/node_modules/abstract-leveldown/abstract-leveldown.js:257
      throw new Error('Legacy range options ("start" and "end") have been removed')
            ^
```

level@7.0.0, level-exists@2.0.2

see also https://github.com/Level/community/issues/86

**Comment by juliangruber** [comment]
Thanks for reporting! https://github.com/juliangruber/level-exists/releases/tag/v3.0.0

**Comment by rlidwka** [comment]
You added `package-lock.json`, may I ask why? Is that intentional?

*It's used a lot for self-contained programs, but pretty rare thing to see for a library.*

**Comment by juliangruber** [comment]
> You added `package-lock.json`, may I ask why? Is that intentional?
> 
> 
> 
> *It's used a lot for self-contained programs, but pretty rare thing to see for a library.*

I don't think about removing files from bundles usually, if you care then we could add it to the ignore file
