### ISSUE TITLE
Would be good to document what the recent version bump contains ...

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/level-exists#6]
Maybe add a changelog in README.md?

**Comment by juliangruber** [comment]
is that hard to tell looking at the git history?

**Comment by binarykitchen** [comment]
no but still, a changelog would be nice. the recent commits reverted something. had to open 8 commits to understand what has changed and what not.

**Comment by juliangruber** [comment]
i'll try to write more complete commit messages

**Comment by binarykitchen** [comment]
ta
